name: CI
# Commenting out pull_request event since BrowserStack doesn't seem to want to
# let me open 2 tunnels at the same time.
# on: [push, pull_request]
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn
      - name: Lint
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn lint
      - name: Test
        uses: ianwalter/bsl@v2.0.1
        with:
          args: yarn test
        env:
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
