name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      hub:
        image: elgalu/selenium:3.1
        ports:
          - 4444:4444
        env:
          SELENIUM_HUB_HOST: hub
          SELENIUM_HUB_PORT: 4444
          GRID: true
          CHROME: false
          FIREFOX: false
      firefox:
        image: elgalu/selenium:3.1
        env:
          SELENIUM_HUB_HOST: hub
          SELENIUM_HUB_PORT: 4444
          GRID: false
          CHROME: false
          FIREFOX: true
          VIDEO: false
    steps:
      - name: Checkout
        uses: actions/checkout@v1.2.0
      - name: Install
        uses: ianwalter/selenium-standalone@master
        with:
          args: yarn
      - name: Lint
        uses: ianwalter/selenium-standalone@master
        with:
          args: yarn lint
      - name: Test
        uses: ianwalter/selenium-standalone@master
        with:
          args: yarn test
        env:
          SELENIUM_HUB_HOST: hub
